// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/sllt/kite-layout/internal/bootstrap"
	"github.com/sllt/kite-layout/internal/server"
	"github.com/sllt/kite-layout/pkg/app"
)

// Injectors from wire.go:

func NewWire() (*app.App, func(), error) {
	kiteApp := bootstrap.NewKiteApp()
	logger := bootstrap.NewLogger(kiteApp)
	migrateServer := server.NewMigrateServer(kiteApp, logger)
	appApp := newApp(migrateServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var serverSet = wire.NewSet(server.NewMigrateServer)

// build App
func newApp(
	migrateServer *server.MigrateServer,
) *app.App {
	return app.NewApp(app.WithServer(migrateServer), app.WithName("demo-migrate"))
}
