// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/sllt/kite-layout/internal/server"
	"github.com/sllt/kite-layout/pkg/app"
	"github.com/sllt/kite-layout/pkg/log"
	"github.com/sllt/kite/pkg/kite"
)

// Injectors from wire.go:

func NewWire() (*app.App, func(), error) {
	kiteApp := NewKiteApp()
	logger := NewLogger(kiteApp)
	migrateServer := server.NewMigrateServer(kiteApp, logger)
	appApp := newApp(migrateServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var serverSet = wire.NewSet(server.NewMigrateServer)

// NewKiteApp creates a kite.App.
func NewKiteApp() *kite.App {
	return kite.New()
}

// NewLogger extracts kite's logger from the container and wraps it.
func NewLogger(app2 *kite.App) *log.Logger {
	return log.NewLogger(app2.Container().Logger)
}

// build App
func newApp(
	migrateServer *server.MigrateServer,
) *app.App {
	return app.NewApp(app.WithServer(migrateServer), app.WithName("demo-migrate"))
}
