// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/sllt/kite-layout/internal/handler"
	"github.com/sllt/kite-layout/internal/repository"
	"github.com/sllt/kite-layout/internal/router"
	"github.com/sllt/kite-layout/internal/server"
	"github.com/sllt/kite-layout/internal/service"
	"github.com/sllt/kite-layout/pkg/jwt"
	"github.com/sllt/kite-layout/pkg/log"
	"github.com/sllt/kite-layout/pkg/sid"
	"github.com/google/wire"
	"github.com/sllt/kite/pkg/kite"
	"github.com/sllt/kite/pkg/kite/infra"
)

// Injectors from wire.go:

func NewWire() (*kite.App, func(), error) {
	kiteApp := NewKiteApp()
	jwtJWT := jwt.NewJwt(kiteApp)
	logger := NewLogger(kiteApp)
	handlerHandler := handler.NewHandler(logger)
	db := NewDB(kiteApp)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	routerDeps := router.RouterDeps{
		App:         kiteApp,
		Logger:      logger,
		JWT:         jwtJWT,
		UserHandler: userHandler,
	}
	httpServerReady := server.NewHTTPServer(routerDeps)
	app := newApp(kiteApp, httpServerReady)
	return app, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewRepository, repository.NewTransaction, repository.NewUserRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler)

var serverSet = wire.NewSet(server.NewHTTPServer)

// NewKiteApp creates a new kite.App.
func NewKiteApp() *kite.App {
	return kite.New()
}

// NewLogger extracts kite's logger from the container and wraps it.
func NewLogger(app *kite.App) *log.Logger {
	return log.NewLogger(app.Container().Logger)
}

// NewDB extracts infra.DB from the kite app's container
func NewDB(app *kite.App) infra.DB {
	return app.Container().SQL
}

// newApp ensures routes are registered (via HTTPServerReady dependency)
// then returns the kite app for lifecycle management.
func newApp(
	app *kite.App,
	_ *server.HTTPServerReady,
) *kite.App {
	return app
}
