// Code generated by kite-cli. DO NOT EDIT.
// versions:
// 	kite-cli v0.1.0
// 	kite v0.1.0
// 	source: user.proto

package user

import (
	"context"

	"github.com/sllt/kite/pkg/kite"
	"github.com/sllt/kite/pkg/kite/infra"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	healthpb "google.golang.org/grpc/health/grpc_health_v1"
)

// NewUserServiceKiteServer creates a new instance of UserServiceKiteServer
func NewUserServiceKiteServer() *UserServiceKiteServer {
	return &UserServiceKiteServer{
		health: getOrCreateHealthServer(), // Initialize the health server
	}
}

// UserServiceServerWithKite is the interface for the server implementation
type UserServiceServerWithKite interface {
	Register(*kite.Context) (any, error)
	Login(*kite.Context) (any, error)
	GetProfile(*kite.Context) (any, error)
	UpdateProfile(*kite.Context) (any, error)
}

// UserServiceServerWrapper wraps the server and handles request and response logic
type UserServiceServerWrapper struct {
	UserServiceServer
	*healthServer
	Container *infra.Container
	server    UserServiceServerWithKite
}




// Unary method handler for Register
func (h *UserServiceServerWrapper) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	gctx := h.getKiteContext(ctx, &RegisterRequestWrapper{ctx: ctx, RegisterRequest: req})

	res, err := h.server.Register(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*RegisterResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}

	return resp, nil
}
// Unary method handler for Login
func (h *UserServiceServerWrapper) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	gctx := h.getKiteContext(ctx, &LoginRequestWrapper{ctx: ctx, LoginRequest: req})

	res, err := h.server.Login(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*LoginResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}

	return resp, nil
}
// Unary method handler for GetProfile
func (h *UserServiceServerWrapper) GetProfile(ctx context.Context, req *GetProfileRequest) (*GetProfileResponse, error) {
	gctx := h.getKiteContext(ctx, &GetProfileRequestWrapper{ctx: ctx, GetProfileRequest: req})

	res, err := h.server.GetProfile(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*GetProfileResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}

	return resp, nil
}
// Unary method handler for UpdateProfile
func (h *UserServiceServerWrapper) UpdateProfile(ctx context.Context, req *UpdateProfileRequest) (*UpdateProfileResponse, error) {
	gctx := h.getKiteContext(ctx, &UpdateProfileRequestWrapper{ctx: ctx, UpdateProfileRequest: req})

	res, err := h.server.UpdateProfile(gctx)
	if err != nil {
		return nil, err
	}

	resp, ok := res.(*UpdateProfileResponse)
	if !ok {
		return nil, status.Errorf(codes.Unknown, "unexpected response type %T", res)
	}

	return resp, nil
}

// mustEmbedUnimplementedUserServiceServer ensures implementation
func (h *UserServiceServerWrapper) mustEmbedUnimplementedUserServiceServer() {}

// RegisterUserServiceServerWithKite registers the server
func RegisterUserServiceServerWithKite(app *kite.App, srv UserServiceServerWithKite) {
	registerServerWithKite(app, srv, func(s grpc.ServiceRegistrar, srv any) {
		wrapper := &UserServiceServerWrapper{
			server: srv.(UserServiceServerWithKite),
			healthServer: getOrCreateHealthServer(),
		}

		RegisterUserServiceServer(s, wrapper)

		wrapper.Server.SetServingStatus("Hello", healthpb.HealthCheckResponse_SERVING)
	})
}

// getKiteContext creates Kite context
func (h *UserServiceServerWrapper) getKiteContext(ctx context.Context, req kite.Request) *kite.Context {
	return &kite.Context{
		Context:   ctx,
		Container: h.Container,
		Request:   req,
	}
}
